import { useMemo, useState } from "react";
import { Pencil, Search, Star, Users, ChevronDown } from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import { repository } from "../../services/repository";
import GlassModal from "../../components/GlassModal";
import EmptyState from "../../components/EmptyState";

export default function Clubs(){
 const {session}=useAuth(); const [items,setItems]=useState(()=>repository.list("clubs")); const [q,setQ]=useState(""); const [selected,setSelected]=useState(null); const [reviewOpen,setReviewOpen]=useState(false); const [form,setForm]=useState({joinedDate:"",rating:0,review:""});
 const filtered=useMemo(()=>items.filter(x=>`${x.clubName} ${x.clubType}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
 const submit=e=>{e.preventDefault(); if(!selected)return; const next=repository.add("clubs",{clubId:selected.id,clubName:selected.clubName,clubType:selected.clubType,joinedDate:form.joinedDate,rating:Number(form.rating),review:form.review,authorEmail:session.user.email,authorName:session.user.fullName}); setItems(next);setReviewOpen(false);setForm({joinedDate:"",rating:0,review:""});};
 return <div className="content-page"><div className="page-header"><div><p className="eyebrow">EXPLORE</p><h1>Club Reviews</h1><p>Discover student experiences across campus clubs.</p></div></div><div className="filter-bar"><div className="search-box"><Search/><input placeholder="Search by club name or type..." value={q} onChange={e=>setQ(e.target.value)}/></div></div>
 {filtered.length===0?<EmptyState message="No club information yet."/>:<div className="card-grid">{filtered.map(club=><ClubCard key={club.id} club={club} reviews={items.filter(r=>r.clubId===club.id)} onReview={()=>{setSelected(club);setReviewOpen(true)}} onRead={()=>setSelected({...club,read:true})}/>)}</div>}
 <GlassModal open={!!selected?.read} onClose={()=>setSelected(null)} title={selected?.clubName||"Club Reviews"} subtitle={selected?.clubType}><div className="reviews-list">{items.filter(r=>r.clubId===selected?.id).length===0?<EmptyState message="No reviews yet."/>:items.filter(r=>r.clubId===selected?.id).map(r=><div className="review-row" key={r.id}><strong>{r.authorName}</strong><Stars value={r.rating}/><p>{r.review}</p></div>)}</div></GlassModal>
 <GlassModal open={reviewOpen} onClose={()=>setReviewOpen(false)} title={`Review ${selected?.clubName||"Club"}`} subtitle="Share your experience with this club."><form className="form-stack" onSubmit={submit}><label><span>When did you join?</span><input type="date" value={form.joinedDate} onChange={e=>setForm({...form,joinedDate:e.target.value})} required/></label><label><span>Rating</span><div className="rating-input">{[1,2,3,4,5].map(n=><button type="button" key={n} className={n<=form.rating?"star active":"star"} onClick={()=>setForm({...form,rating:n})}><Star fill="currentColor"/></button>)}</div></label><label><span>Your Review</span><textarea value={form.review} onChange={e=>setForm({...form,review:e.target.value})} required/></label><button className="primary-button">Submit Review</button></form></GlassModal>
 </div>
}
function ClubCard({club,reviews,onReview,onRead}){const avg=reviews.length?reviews.reduce((a,b)=>a+Number(b.rating||0),0)/reviews.length:0;return <article className="club-card glass-panel"><div className="club-icon"><Users/></div><h3>{club.clubName}</h3><p>{club.clubType}</p><div className="stars-line"><Stars value={avg}/><span>{reviews.length?avg.toFixed(1):"—"}</span></div><div className="club-actions"><button onClick={onRead}>Read Reviews <ChevronDown/></button><button onClick={onReview} aria-label="Write review"><Pencil/></button></div></article>}
function Stars({value}){return <span className="stars">{[1,2,3,4,5].map(n=><Star key={n} fill={n<=Math.round(value)?"currentColor":"none"}/>)}</span>}