import { useMemo, useRef, useState } from "react";
import { Plus, Search, ChevronDown, Heart, MessageCircle, Trophy } from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import { repository } from "../../services/repository";
import GlassModal from "../../components/GlassModal";
import EmptyState from "../../components/EmptyState";

const empty={hackathonName:"",semester:"",participationType:"",teamSize:"",role:"",technologies:"",experience:"",date:""};

export default function HackathonExperiences(){
 const {session}=useAuth(); const bottomRef=useRef(null); const [items,setItems]=useState(()=>repository.list("hackathons")); const [q,setQ]=useState(""); const [filters,setFilters]=useState({hackathonName:"",role:"",semester:"",participationType:"",technology:"",year:""}); const [form,setForm]=useState(empty); const [open,setOpen]=useState(false); const [expanded,setExpanded]=useState(null);
 const filtered=useMemo(()=>items.filter(x=>{const hay=`${x.hackathonName} ${x.role} ${x.technologies}`.toLowerCase(); return (!q||hay.includes(q.toLowerCase())) && (!filters.hackathonName||x.hackathonName===filters.hackathonName)&&(!filters.role||x.role===filters.role)&&(!filters.semester||x.semester===filters.semester)&&(!filters.participationType||x.participationType===filters.participationType)&&(!filters.technology||x.technologies.split(",").map(s=>s.trim()).includes(filters.technology))&&(!filters.year||x.date?.startsWith(filters.year));}),[items,q,filters]);
 const submit=e=>{e.preventDefault(); const next=repository.add("hackathons",{...form,teamSize:form.participationType==="Team"?form.teamSize:"",authorEmail:session.user.email,authorName:session.user.fullName}); setItems(next);setForm(empty);setOpen(false);};
 const set=(k,v)=>setForm({...form,[k]:v});
 return <div className="content-page">
  <Header title="Hackathon Experiences" subtitle="Build. Compete. Learn from real student journeys." onPlus={()=>bottomRef.current?.scrollIntoView({behavior:"smooth"})}/>
  <div className="filter-bar"><div className="search-box"><Search/><input placeholder="Search by hackathon name, technology, or keyword..." value={q} onChange={e=>setQ(e.target.value)}/></div>{["hackathonName","role","semester","participationType","technology","year"].map(k=><Filter key={k} label={pretty(k)} value={filters[k]} options={[...new Set(items.flatMap(x=>k==="technology"?(x.technologies||"").split(",").map(s=>s.trim()):[x[k]]).filter(Boolean))]} onChange={v=>setFilters({...filters,[k]:v})}/>)}<button className="clear-button" onClick={()=>{setQ("");setFilters({hackathonName:"",role:"",semester:"",participationType:"",technology:"",year:""})}}>Clear Filters</button></div>
  {filtered.length===0?<EmptyState message="No hackathon experiences yet." action={<button className="primary-button" onClick={()=>bottomRef.current?.scrollIntoView({behavior:"smooth"})}>Share Your Experience</button>}/>:<div className="card-grid">{filtered.map(x=><article className="data-card glass-panel" key={x.id}><div className="date-pill">{x.date}</div><div className="card-top"><div className="company-mark"><Trophy/></div><div><h3>{x.hackathonName}</h3><p>{x.authorName||"Student"} · {x.role}</p></div></div><div className="chips"><span>{x.semester}</span><span>{x.participationType}</span>{x.teamSize&&<span>Group {x.teamSize}</span>}<span>{x.technologies}</span></div><p className={expanded===x.id?"experience full":"experience"}>{x.experience}</p><button className="read-more" onClick={()=>setExpanded(expanded===x.id?null:x.id)}>{expanded===x.id?"Show Less":"Read More"}<ChevronDown/></button><div className="card-footer"><span><Heart/> 0</span><span><MessageCircle/> 0</span></div></article>)}</div>}
  <section ref={bottomRef} className="contribute-section glass-panel"><div><p className="eyebrow">CONTRIBUTE</p><h2>Share Your Hackathon Experience</h2><p>Help build a knowledge base for future participants.</p></div><button className="primary-button" onClick={()=>setOpen(true)}><Plus/> Share Your Experience</button></section>
  <GlassModal open={open} onClose={()=>setOpen(false)} title="Share Your Hackathon Experience" subtitle="Help build a knowledge base for future participants." wide><form className="form-grid" onSubmit={submit}>
   <Field label="Hackathon Name" value={form.hackathonName} onChange={v=>set("hackathonName",v)} required/><SelectField label="Semester" value={form.semester} options={["Semester 1","Semester 2","Semester 3","Semester 4","Semester 5","Semester 6","Semester 7","Semester 8"]} onChange={v=>set("semester",v)} required/><SelectField label="Participation Type" value={form.participationType} options={["Individual","Team"]} onChange={v=>set("participationType",v)} required/>{form.participationType==="Team"&&<Field label="Team Size" value={form.teamSize} onChange={v=>set("teamSize",v)} required/>}<Field label="Your Role" value={form.role} onChange={v=>set("role",v)} required/><Field label="Technologies Used" value={form.technologies} onChange={v=>set("technologies",v)} required/><TextArea label="Experience Summary" value={form.experience} onChange={v=>set("experience",v)} required full/><Field label="Date" value={form.date} onChange={v=>set("date",v)} required/><div className="form-actions full"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-button">Share Experience</button></div>
  </form></GlassModal>
 </div>
}
function Header({title,subtitle,onPlus}){return <div className="page-header"><div><p className="eyebrow">EXPLORE</p><h1>{title}</h1><p>{subtitle}</p></div><button className="plus-button" onClick={onPlus}><Plus/></button></div>}
function pretty(k){return ({hackathonName:"Hackathon",role:"Role",semester:"Semester",participationType:"Participation Type",technology:"Technology",year:"Year"})[k]||k}
function Filter({label,value,onChange,options}){return <label className="select-box"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option value="">{label}</option>{options.map(o=><option key={o}>{o}</option>)}</select><ChevronDown/></label>}
function Field({label,value,onChange,required}){return <label><span>{label}{required&&" *"}</span><input value={value} onChange={e=>onChange(e.target.value)} required={required}/></label>}
function SelectField({label,value,onChange,options,required}){return <label><span>{label}{required&&" *"}</span><select value={value} onChange={e=>onChange(e.target.value)} required={required}><option value="">Select option</option>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function TextArea({label,value,onChange,required,full}){return <label className={full?"full":""}><span>{label}{required&&" *"}</span><textarea value={value} onChange={e=>onChange(e.target.value)} required={required}/></label>}