import { useState } from "react";
import { Camera, Edit3, KeyRound, UserRound, Mail, GraduationCap, Users, FileText, Trophy, BookOpen } from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import { repository } from "../../services/repository";
import GlassModal from "../../components/GlassModal";

export default function Profile(){
 const {session,updateStudent}=useAuth(); const u=session?.user||{}; const [editing,setEditing]=useState(false); const [form,setForm]=useState({firstName:u.firstName||"",middleName:u.middleName||"",lastName:u.lastName||"",email:u.email||"",password:u.password||"",batch:u.batch||"",department:u.department||""});
 const submit=e=>{e.preventDefault();updateStudent({...form,fullName:[form.firstName,form.middleName,form.lastName].filter(Boolean).join(" ")});setEditing(false)};
 const counts={interviews:repository.list("interviews").filter(x=>x.authorEmail===u.email).length,hackathons:repository.list("hackathons").filter(x=>x.authorEmail===u.email).length,clubs:repository.list("clubs").filter(x=>x.authorEmail===u.email).length,resources:repository.list("resources").filter(x=>x.authorEmail===u.email).length};
 return <div className="profile-page"><div className="profile-left"><section className="profile-card glass-panel"><div className="profile-avatar"><UserRound/><button><Camera/></button></div><h2>{u.fullName||"Student"}</h2><p>{u.department||"Department not set"} {u.batch&&` · ${u.batch}`}</p><p>University of Visvesvaraya College of Engineering</p><div className="points-box"><span>Knowledge Points</span><strong>{u.knowledgePoints??0}</strong></div></section><section><h2>My Contributions</h2><p className="muted">Your activity across different sections</p><div className="contribution-list"><Contribution icon={BriefcaseIcon} title="Interview Experiences" count={counts.interviews}/><Contribution icon={Trophy} title="Hackathon Experiences" count={counts.hackathons}/><Contribution icon={Users} title="Club Reviews" count={counts.clubs}/><Contribution icon={BookOpen} title="Academic Resources" count={counts.resources}/></div></section></div>
 <div className="profile-right"><section className="glass-panel profile-info"><div className="section-title"><h2><UserRound/>Personal Information</h2><button className="primary-button" onClick={()=>setEditing(true)}><Edit3/> Edit Profile</button></div><div className="info-grid"><Info label="First Name" value={u.firstName}/><Info label="Middle Name" value={u.middleName}/><Info label="Last Name" value={u.lastName}/><Info label="Email Address" value={u.email}/><Info label="Password" value="••••••••" /><Info label="Batch / Semester" value={u.batch}/><Info label="Department" value={u.department}/></div></section><section className="glass-panel about-box"><h2><FileText/>About Me</h2><p>Update your profile information here. A future version can store an About Me field in SQL.</p></section></div>
 <GlassModal open={editing} onClose={()=>setEditing(false)} title="Edit Profile" subtitle="Update your personal information."><form className="form-stack" onSubmit={submit}><div className="two-col"><Field label="First Name" value={form.firstName} onChange={v=>setForm({...form,firstName:v})}/><Field label="Middle Name" value={form.middleName} onChange={v=>setForm({...form,middleName:v})}/></div><Field label="Last Name" value={form.lastName} onChange={v=>setForm({...form,lastName:v})}/><Field label="Email Address" value={form.email} onChange={v=>setForm({...form,email:v})} type="email"/><Field label="Password" value={form.password} onChange={v=>setForm({...form,password:v})} type="password"/><div className="two-col"><Field label="Batch / Semester" value={form.batch} onChange={v=>setForm({...form,batch:v})}/><Field label="Department" value={form.department} onChange={v=>setForm({...form,department:v})}/></div><button className="primary-button">Save Changes</button></form></GlassModal>
 </div>
}
function Contribution({icon:Icon,title,count}){return <div className="contribution-item"><span className="section-icon"><Icon/></span><strong>{title}</strong><span className="contribution-count">{count}</span></div>}
function Info({label,value}){return <div className="info-item"><span>{label}</span><strong>{value||"Not set"}</strong></div>}
function Field({label,value,onChange,type="text"}){return <label><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function BriefcaseIcon(){return <KeyRound/>}