import { useMemo, useState } from "react";
import { FileText, Search, Upload, Crown, ExternalLink, ChevronDown } from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import { repository } from "../../services/repository";
import GlassModal from "../../components/GlassModal";
import EmptyState from "../../components/EmptyState";

export default function Resources(){
 const {session}=useAuth(); const [items,setItems]=useState(()=>repository.list("resources")); const [q,setQ]=useState(""); const [subject,setSubject]=useState(""); const [semester,setSemester]=useState(""); const [open,setOpen]=useState(false); const [form,setForm]=useState({title:"",description:"",semester:"",subject:"",resourceLink:"",premium:false});
 const filtered=useMemo(()=>items.filter(x=>`${x.title} ${x.subject}`.toLowerCase().includes(q.toLowerCase())&&(!subject||x.subject===subject)&&(!semester||x.semester===semester)),[items,q,subject,semester]);
 const submit=e=>{e.preventDefault(); const next=repository.add("resources",{...form,authorEmail:session.user.email,authorName:session.user.fullName});setItems(next);setOpen(false);setForm({title:"",description:"",semester:"",subject:"",resourceLink:"",premium:false});};
 return <div className="content-page"><div className="page-header"><div><p className="eyebrow">EXPLORE</p><h1>Academic Resources</h1><p>Find study materials, notes, papers and more, shared by your seniors.</p></div></div><div className="filter-bar"><div className="search-box"><Search/><input placeholder="Search by title or subject..." value={q} onChange={e=>setQ(e.target.value)}/></div><select value={subject} onChange={e=>setSubject(e.target.value)}><option value="">Subject</option>{[...new Set(items.map(x=>x.subject).filter(Boolean))].map(x=><option key={x}>{x}</option>)}</select><select value={semester} onChange={e=>setSemester(e.target.value)}><option value="">Semester</option>{[...new Set(items.map(x=>x.semester).filter(Boolean))].map(x=><option key={x}>{x}</option>)}</select></div>
 {filtered.length===0?<EmptyState message="No academic resources yet." action={<button className="primary-button" onClick={()=>setOpen(true)}><Upload/> Upload a Resource</button>}/>:<div className="resource-grid">{filtered.map(x=><article className="resource-card glass-panel" key={x.id}><div className="file-icon"><FileText/></div>{x.premium&&<span className="premium-badge"><Crown/> Premium</span>}<h3>{x.title}</h3><p>{x.description}</p><div className="chips"><span>{x.subject}</span><span>{x.semester}</span></div><a href={x.resourceLink} target="_blank" rel="noreferrer" className="primary-button">View File <ExternalLink/></a></article>)}</div>}
 <section className="contribute-section glass-panel"><div><p className="eyebrow">CONTRIBUTE</p><h2>Upload a Resource</h2><p>Share your notes, papers or study materials to help your juniors.</p></div><button className="primary-button" onClick={()=>setOpen(true)}><Upload/> Upload Resource</button></section>
 <GlassModal open={open} onClose={()=>setOpen(false)} title="Upload a Resource" subtitle="Share a study resource with your campus community."><form className="form-stack" onSubmit={submit}><label><span>Title *</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label><span>Description *</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></label><div className="two-col"><label><span>Semester *</span><select value={form.semester} onChange={e=>setForm({...form,semester:e.target.value})} required><option value="">Select</option>{Array.from({length:8},(_,i)=><option key={i}>Semester {i+1}</option>)}</select></label><label><span>Subject *</span><input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} required/></label></div><label><span>Resource Link *</span><input type="url" value={form.resourceLink} onChange={e=>setForm({...form,resourceLink:e.target.value})} required/></label><button className="primary-button">Upload Resource</button></form></GlassModal>
 </div>
}