import { useMemo, useState } from "react";
import { BriefcaseBusiness, CalendarDays, ChevronDown, Edit3, Plus, Search } from "lucide-react";
import { repository } from "../../services/repository";
import GlassModal from "../../components/GlassModal";
import EmptyState from "../../components/EmptyState";

const empty={companyName:"",role:"",package:"",applicationDeadline:"",eligibilityCriteria:"",selectionProcess:""};

export default function TpoPlacements(){
 const [items,setItems]=useState(()=>repository.list("placements")); const [q,setQ]=useState(""); const [open,setOpen]=useState(false); const [editing,setEditing]=useState(null); const [form,setForm]=useState(empty);
 const filtered=useMemo(()=>items.filter(x=>`${x.companyName} ${x.role}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
 const start=(item=null)=>{setEditing(item);setForm(item?{...item}:empty);setOpen(true)};
 const submit=e=>{e.preventDefault();let next;if(editing){next=repository.update("placements",editing.id,form)}else{next=repository.add("placements",form)}setItems(next);setOpen(false)};
 return <div className="content-page"><div className="page-header"><div><p className="eyebrow">TPO ADMIN</p><h1>Welcome, TPO Admin!</h1><p>Manage and update placement information for students.</p></div></div><div className="admin-actions"><button className="admin-action-card glass-panel" onClick={()=>start()}><span className="section-icon"><Plus/></span><span><strong>Add Placement Information</strong><small>Add new job opportunities, company details, eligibility criteria and more.</small></span><ChevronDown/></button><button className="admin-action-card glass-panel" onClick={()=>document.getElementById("placement-list")?.scrollIntoView({behavior:"smooth"})}><span className="section-icon"><BriefcaseBusiness/></span><span><strong>View Placement Information</strong><small>View and manage existing placement information.</small></span><ChevronDown/></button></div><section id="placement-list"><div className="section-heading-row"><div><h2>Placement Information</h2><p>View and manage all placement opportunities.</p></div><div className="search-box compact"><Search/><input placeholder="Search by company name or role..." value={q} onChange={e=>setQ(e.target.value)}/></div></div>{filtered.length===0?<EmptyState message="No placement information yet." action={<button className="primary-button" onClick={()=>start()}><Plus/> Add Placement</button>}/>:<div className="placement-grid">{filtered.map(x=><article className="placement-card glass-panel" key={x.id}><div className="company-mark"><BriefcaseBusiness/></div><h3>{x.companyName}</h3><p>{x.role}</p><div className="placement-row"><span>Package</span><strong>{x.package}</strong></div><div className="placement-row"><span>Eligibility</span><p>{x.eligibilityCriteria}</p></div><div className="placement-row"><span><CalendarDays/>Application Deadline</span><strong>{x.applicationDeadline}</strong></div><div className="card-actions"><button className="secondary-button" onClick={()=>start(x)}><Edit3/> Edit</button><button className="primary-button" onClick={()=>start(x)}>View Details <ChevronDown/></button></div></article>)}</div>}</section>
 <GlassModal open={open} onClose={()=>setOpen(false)} title={editing?"Edit Placement Information":"Add Placement Information"} subtitle="Enter the details of the placement opportunity." wide><form className="form-stack" onSubmit={submit}><Field label="Company Name" value={form.companyName} set={v=>setForm({...form,companyName:v})} required/><Field label="Role / Job Title" value={form.role} set={v=>setForm({...form,role:v})} required/><Field label="Package (CTC)" value={form.package} set={v=>setForm({...form,package:v})} required/><Field label="Application Deadline" value={form.applicationDeadline} set={v=>setForm({...form,applicationDeadline:v})} type="date" required/><Field label="Eligibility Criteria" value={form.eligibilityCriteria} set={v=>setForm({...form,eligibilityCriteria:v})} area required/><Field label="Selection Process / Details" value={form.selectionProcess} set={v=>setForm({...form,selectionProcess:v})} area required/><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancel</button><button type="submit" className="primary-button">{editing?"Save Changes":"Add Placement"}</button></div></form></GlassModal>
 </div>
}
function Field({label,value,set,type="text",area,required}){return <label><span>{label} {required&&"*"}</span>{area?<textarea value={value} onChange={e=>set(e.target.value)} required={required}/>:<input type={type} value={value} onChange={e=>set(e.target.value)} required={required}/>}</label>}